url: https://neonconsulting.github.io/
baseurl:

# Site settings
title: Neon Consulting
email: all@neonconsulting.au
description: "Neon Consulting provide engineering services specialising in the the civil discipline."


# Team names, titles and social links
people:
- name: Craig Caplick
  pic: 1
  position: Lead Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Paul Mashford
  pic: 2
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Cairns
  - line: Australia

# Build settings
markdown: kramdown
permalink: pretty
